services:
# Web Application Firewall (ModSecurity + Nginx)
  waf:
    build:
      context: ./waf-nginx
      dockerfile: Dockerfile
    container_name: Movie_waf_nginx
    ports:
      - "80:80"                                   # Public entry point for all traffic
      - "443:443"
    environment:
      - PROTOCOL=https
      - NDN_VALIDATE_CERT=0
      - PARANOIA=3                                # Security detection level (3: High/Strict)
      - DETECTION_ONLY=0                          # Block mode for active WAF protection
      - MODSEC_RULE_ENGINE=On                     # Ensure ModSecurity rule engine is enabled
      - BACKEND=http://frontend:5173              # Default destination for frontend assets
      - LOCATION=/api                             # Route pattern for backend redirection
      - PROXY_BACKEND=http://backend-nest:3000    # Forward /api requests to NestJS API
      - SSL_CERT=/etc/nginx/conf/server.crt
      - SSL_KEY=/etc/nginx/conf/server.key
      - TERMINATED_ENV_VARS=proxy_http_version 1.1; proxy_set_header Upgrade $$http_upgrade; proxy_set_header Connection "upgrade";
    depends_on:
      frontend:
        condition: service_started
      backend-nest:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - moviedb-network

# HashiCorp Vault: Centralized secret management
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: Movie_vault
    env_file:
      - ./.env
    secrets:
      - initial_secrets
#    ports:
#      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - moviedb-network

# PostgreSQL: Relational database
  postgres:
    image: pgvector/pgvector:pg16
    container_name: Movie_db
    env_file:
      - ./.env
    secrets:
      - postgres_password
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - ./backend-python/init_db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - moviedb-network

# FastAPI Backend
  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: Movie_fast_api
    env_file:
      - ./.env
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN_FILE=/vault/file/vault_root_token
    volumes:
      - ./backend-python:/app
      - ./backend-python/dbCSV:/dbCSV
      - vault_data:/vault/file:ro
#    ports:
#      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 60s
      retries: 60
    depends_on:
      postgres:
        condition: service_healthy
      vault:
        condition: service_healthy
    networks:
      - moviedb-network

# MongoDB: NoSQL database
  mongodb:
    image: mongo:7
    container_name: Movie_mongodb
    command: mongod --quiet
    env_file:
      - ./.env
    secrets:
      - mongo_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
#    ports:
#      - "27017:27017"
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      vault:
        condition: service_healthy    
    networks:
      - moviedb-network

# NestJS Backend
  backend-nest:
    container_name: Movie_nest_api
    build: 
      context: ./backend-nest
      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
    env_file:
      - ./.env
    secrets:
      - postgres_password
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN_FILE=/vault/file/vault_root_token
    volumes:
      - ./backend-nest:/app
      - /app/node_modules
      - vault_data:/vault/file:ro
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      backend-python:
        condition: service_healthy
      vault:
        condition: service_healthy
    networks:
      - moviedb-network

# Frontend: UI Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: Movie_frontend
    env_file:
      - ./.env
#    ports:
#      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-nest
    networks:
      - moviedb-network
    restart: unless-stopped

# External secret definitions
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
  initial_secrets:
    file: ./secrets/initial_secrets.json

volumes:
  postgres_data:
  mongodb_data:
  mongodb_config:
  vault_data:

networks:
  moviedb-network:
    driver: bridge
