services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: Movie_db
    env_file:
      - .env
    volumes:
      - ./backend-python/init_db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - moviedb-network
    
  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: Movie_fast_api
    env_file:
      - ./.env
    volumes:
      - ./backend-python:/app
      - ./backend-python/dbCSV:/dbCSV
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - moviedb-network

  backend-nest:
    container_name: Movie_nest_api
    build: 
      context: ./backend-nest
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./backend-nest:/app
      - /app/node_modules
    depends_on:
      - postgres
      - backend-python
    networks:
      - moviedb-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: Movie_frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-nest
    networks:
      - moviedb-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  moviedb-network:
    driver: bridge

  
