import type { AuthResponse, TwoFaSetupResponse } from '@/types'
import { apiClient } from './client'

/**
 * Two-Factor Authentication API Service
 * Manages the lifecycle of TOTP/2FA security including setup, activation, verification, and teardown.
 */
export const twofaApi = {
  /**
   * Initializes the 2FA setup process.
   * Retrieves the secret and a generated QR code URL for authenticator apps.
   * @returns A promise resolving to the 2FA setup details (QR code, secret, backup codes).
   */
  setup: async (): Promise<TwoFaSetupResponse> => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const res = await apiClient.get<any>('/2fa/setup')
    const payload = res.data

    // Normalize possible backend shapes definitively
    const qr_code_url: string = payload.qr_code_url ?? payload.qrcode ?? payload.qr ?? ''
    const secret: string = payload.secret ?? payload.key ?? ''

    return { qr_code_url, secret, backup_codes: payload.backup_codes }
  },

  /**
   * Confirms and activates 2FA for the user after scanning the QR code.
   * @param code - The 6-digit TOTP code generated by the authenticator app.
   * @returns A promise confirming successful activation.
   */
  activate: async (code: string): Promise<{ message: string }> => {
    const res = await apiClient.post<{ message: string }>('/2fa/activate', { token: code })
    return res.data
  },

  /**
   * Verifies the 2FA code during the authentication sequence.
   * Leverages the HTTP-only temporary secure cookie automatically attached by the client.
   * @param code - The 6-digit TOTP code generated by the authenticator app.
   * @returns A promise resolving to the full AuthResponse with the permanent session payload.
   */
  verify: async (code: string): Promise<AuthResponse> => {
    const res = await apiClient.post<AuthResponse>('/2fa/verify', { token: code })
    return res.data
  },

  /**
   * Disables 2FA on the currently logged-in account.
   * @returns A promise confirming successful deactivation.
   */
  disable: async (): Promise<{ message: string }> => {
    const res = await apiClient.delete<{ message: string }>('/2fa/disable')
    return res.data
  }
}
