name: System integration test

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.example .env
          
      - name: Start Containers
        run: docker compose -f docker-compose.dev.yml up -d --build

      - name: Wait for Services
        run: |
          echo "Waiting for nest js and others to be ready .. "
          timeout 240s bash -c 'until curl --silent --fail http://127.0.0.1:3000/health; do sleep 5; done'
          echo "Nestjs api end point is healthy"
          timeout 240s bash -c 'until curl --silent --fail http://127.0.0.1:8000/; do sleep 5; done'
          echo "FastApi is healthy"
          echo "System is up !!" 


      - name: Install HTTPie
        run: pip install httpie

      - name: Run Smoke test
        run: |
          http --check-status --ignore-stdin GET http://localhost:3000/health
          http --check-status --ignore-stdin GET http://localhost:3000/search?=titanic

      - name: Dump Docker logs
        if: failure()
        run: docker compose -f docker-compose.dev.yml logs

      - name: Stop Containers
        run: docker compose -f docker-compose.dev.yml down


      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "CI/CD Pipeline report"
          description: |
            **Status:** ${{ job.status }}
            **Project:** Movie search services
            **Commit:** `${{ github.sha }}`
          status: ${{ job.status }}
          username: Github actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    
