name: System integration test

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.example .env
          
      - name: Start Containers
        run: docker compose -f docker-compose.dev.yml up -d --build

      - name: Wait for Services
        run: |
          echo "Waiting for nest js and others to be ready .. "
          timeout 60s bash -c 'until curl --silent --fail http://localhost:3000/health; do sleep 5; done'
          echo "System is Up!!"

      - name: Run Smoke test
        run: |
          response=$(curl --write-out "‰{http_code}" --silent --output /dev/null "http://localhost:3000/search?q=titanic")
          if [ "$response" -eq 200 ]; then
            echo "Search Endpoint is working!"
          else
            echo "Search failed with status $response"
            exit 1
          fi

      - name: Dump Docker logs
        if: failure()
        run: docker compose -f docker-compose.dev.yml logs

      - name: Stop Containers
        run: docker compose -f docker-compose.dev.yml down


      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "CI/CD Pipeline report"
          description: |
            **Status:** ${{ job.status }}
            **Project:** Movie search services
            **Commit:** `${{ github.sha }}`
          status: ${{ job.status }}
          username: Github actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    
