name: System integration test

on: 
  push:
    branches: ["main", "backend-python", "BasicAuth"]
  pull_request:
    branches: ["main"]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.example .env
          
      - name: Start Containers
        run: docker compose -f docker-compose.dev.yml -f docker-compose.test.yml up -d --build

      - name: Install HTTPie
        run: |
          pip install httpie
          sleep 60

      - name: Smoke test
        run: |
          http --check-status --ignore-stdin GET http://localhost:8000/health
          http --check-status --ignore-stdin GET http://localhost:8000/search?q=John+wick
          http --check-status --ignore-stdin GET http://localhost:3000/health
          http --check-status --ignore-stdin GET http://localhost:3000/search?q=titanic

      - name: Dump Docker logs
        if: failure()
        run: docker compose -f docker-compose.dev.yml logs

      - name: Stop Containers
        run: docker compose -f docker-compose.dev.yml down -v 


      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "CI/CD Pipeline report"
          description: |
            **Status:** ${{ job.status }}
            **Project:** Movie search services
            **Commit:** `${{ github.sha }}`
          status: ${{ job.status }}
          username: Github actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    
