name: System integration test

on: 
  push:
    branches: ["main", "backend-python"]
  pull_request:
    branches: ["main"]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.example .env
          



      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "CI/CD Pipeline report"
          description: |
            **Status:** ${{ job.status }}
            **Project:** Movie search services
            **Commit:** `${{ github.sha }}`
          status: ${{ job.status }}
          username: Github actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    
